name: Add enquiries to project board

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    if: contains(github.event.issue.labels.*.name, 'enquiry')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/MiBe2026/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
